# Generated by Django 5.2.7 on 2026-03-22 13:46

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Department')),
            ],
            options={
                'verbose_name': 'Hospital Department',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Hospital', max_length=100)),
                ('hospital_type', models.CharField(choices=[('Not Set', 'Not Set'), ('Private', 'Private'), ('Public', 'Public')], default='Not set', max_length=20)),
                ('division', models.CharField(blank=True, max_length=40, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('thana', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('website', models.CharField(blank=True, max_length=40, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='Hospital_Images/')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('department', models.ManyToManyField(blank=True, to='hospital.department')),
            ],
            options={
                'verbose_name': 'Hospital',
            },
        ),
    ]
